import ZarankiewiczZ923.ArithmeticKernel
import ZarankiewiczFiniteClosures.ArithmeticKernels
import Zarankiewicz

/-!
This executable audit file is not part of the library API.  Running

`lake env lean AxiomAudit.lean`

prints the axioms used by every theorem that carries the mathematical load.
-/

#print axioms ZarankiewiczZ923.penalty_eq_formula
#print axioms ZarankiewiczZ923.penalty_table
#print axioms ZarankiewiczZ923.penalty_budget_structure
#print axioms ZarankiewiczZ923.classify_degree_profile
#print axioms ZarankiewiczZ923.balanced_deficits_impossible
#print axioms ZarankiewiczZ923.degree_three_deficits_impossible
#print axioms ZarankiewiczZ923.degree_six_deficits_impossible

#print axioms ZarankiewiczFiniteClosures.z10_21_deletion_bound
#print axioms ZarankiewiczFiniteClosures.z11_19_deletion_bound
#print axioms ZarankiewiczFiniteClosures.z11_20_deletion_bound
#print axioms ZarankiewiczFiniteClosures.z11_23_deletion_bound
#print axioms ZarankiewiczFiniteClosures.z10_21_excluded_target
#print axioms ZarankiewiczFiniteClosures.z11_19_excluded_target
#print axioms ZarankiewiczFiniteClosures.z11_20_excluded_target
#print axioms ZarankiewiczFiniteClosures.z11_23_excluded_target
#print axioms ZarankiewiczFiniteClosures.z10_penalty_eq_formula
#print axioms ZarankiewiczFiniteClosures.z10_penalty_table
#print axioms ZarankiewiczFiniteClosures.z10_23_affine_base
#print axioms ZarankiewiczFiniteClosures.z10_23_penalty_budget
#print axioms ZarankiewiczFiniteClosures.z10_23_low_column_impossible
#print axioms ZarankiewiczFiniteClosures.z10_23_two_degree_three_impossible
#print axioms ZarankiewiczFiniteClosures.z10_23_two_six_residue_minima
#print axioms ZarankiewiczFiniteClosures.z10_23_three_six_residue_minima
#print axioms ZarankiewiczFiniteClosures.z10_23_exceptional_profile_impossible
#print axioms ZarankiewiczFiniteClosures.classify_z10_22_degree_profile
#print axioms ZarankiewiczFiniteClosures.z10_22_case_a_impossible
#print axioms ZarankiewiczFiniteClosures.z10_22_case_b_orbit_minima
#print axioms ZarankiewiczFiniteClosures.z10_22_case_b_impossible
#print axioms ZarankiewiczFiniteClosures.z10_22_case_c_impossible
#print axioms ZarankiewiczFiniteClosures.z10_22_case_d_impossible
#print axioms ZarankiewiczFiniteClosures.z12_penalty_eq_formula
#print axioms ZarankiewiczFiniteClosures.z12_penalty_table
#print axioms ZarankiewiczFiniteClosures.z12_23_at_136_profile
#print axioms ZarankiewiczFiniteClosures.z12_23_at_136_pair_equation
#print axioms ZarankiewiczFiniteClosures.z12_23_penalty_budget_structure
#print axioms ZarankiewiczFiniteClosures.classify_z12_23_degree_profile
#print axioms ZarankiewiczFiniteClosures.z12_23_case_one_impossible
#print axioms ZarankiewiczFiniteClosures.z12_23_case_two_impossible
#print axioms ZarankiewiczFiniteClosures.z12_23_case_three_minimum
#print axioms ZarankiewiczFiniteClosures.z12_23_case_four_impossible
#print axioms ZarankiewiczFiniteClosures.z12_23_case_five_impossible
#print axioms ZarankiewiczFiniteClosures.z13_penalty_eq_formula
#print axioms ZarankiewiczFiniteClosures.z13_23_penalty_budget_structure
#print axioms ZarankiewiczFiniteClosures.classify_z13_23_degree_profile
#print axioms ZarankiewiczFiniteClosures.z13_23_clean_row_contradiction
#print axioms ZarankiewiczFiniteClosures.z13_23_case_deficit_bounds

/-! End-to-end matrix theorems. -/

#print axioms Zarankiewicz.Exact.Z9_23.exact_value
#print axioms Zarankiewicz.Exact.Z10_22.exact_value
#print axioms Zarankiewicz.Exact.Z12_23.exact_value
#print axioms Zarankiewicz.Bounds.Z13_23.upper_bound

/-! These closures deliberately retain historical or externally certified
upper bounds as ordinary theorem parameters; the audit confirms that the
closure machinery adds no axiom of its own. -/

#print axioms Zarankiewicz.Exact.DeletionClosures.z10_21_exact
#print axioms Zarankiewicz.Exact.DeletionClosures.z11_19_exact
#print axioms Zarankiewicz.Exact.DeletionClosures.z11_20_exact
#print axioms Zarankiewicz.Exact.DeletionClosures.z10_23_exact_of_upper
#print axioms Zarankiewicz.Exact.DeletionClosures.z11_23_exact
