name = "ZarankiewiczFiniteClosures"
version = "1.5.0"
defaultTargets = ["ZarankiewiczZ923", "ZarankiewiczFiniteClosures"]

[[lean_lib]]
name = "ZarankiewiczZ923"

[[lean_lib]]
name = "ZarankiewiczFiniteClosures"
